// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2DCz3YJthlR5APZ9DjExuZYnrVbMuLcY',
    appId: '1:710290512281:web:94ad42d9013f1de463db08',
    messagingSenderId: '710290512281',
    projectId: 'practical-defb5',
    authDomain: 'practical-defb5.firebaseapp.com',
    storageBucket: 'practical-defb5.appspot.com',
    measurementId: 'G-RPZLF22ZK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY1T4NQRV7i2u-V6Wa_YMwlHbB_wjFp2c',
    appId: '1:710290512281:android:d86d9fa1ed42afe563db08',
    messagingSenderId: '710290512281',
    projectId: 'practical-defb5',
    storageBucket: 'practical-defb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmrYpMFsEpGTL37Mnj4M_744V7oITD6js',
    appId: '1:710290512281:ios:6c2eb31ca56be71463db08',
    messagingSenderId: '710290512281',
    projectId: 'practical-defb5',
    storageBucket: 'practical-defb5.appspot.com',
    iosClientId: '710290512281-a83hb6tdetcisneur8dps3ofj3agmesb.apps.googleusercontent.com',
    iosBundleId: 'com.practical.practical',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmrYpMFsEpGTL37Mnj4M_744V7oITD6js',
    appId: '1:710290512281:ios:6c2eb31ca56be71463db08',
    messagingSenderId: '710290512281',
    projectId: 'practical-defb5',
    storageBucket: 'practical-defb5.appspot.com',
    iosClientId: '710290512281-a83hb6tdetcisneur8dps3ofj3agmesb.apps.googleusercontent.com',
    iosBundleId: 'com.practical.practical',
  );
}
